### PR TITLE
Revert "Update rules_jvm_external to use the Starlark version of aar_import after the native version was removed from Bazel (#1149)"

### PR DESCRIPTION
**Pull request by shs96c**
This reverts commit ba7310ce4a1d8fb14434597fbc7440a4074f7695.

The default label for AAR imports is `@rules_android//android:rules.bzl`. This imports `@rules_android//rules:providers.bzl`, which calls `@rules_android//rules/reexport_providers.bzl`. This means that any downstream user of `rules_jvm_external` with a sufficiently recent version of Bazel needs to add `build --experimental_google_legacy_api` to their `.bazelrc`

That's a significantly breaking change, and one that it's not reasonable to ask our users to do, especially since the vast majority of projects don't use the Android rules.

### CODE REVIEW

**Comment by jin** [comment]
cc @ahumesky

**Comment by jin** [comment]
This looks like https://github.com/bazelbuild/rules_android/issues/219, and we probably cannot roll forward on this until we drop the dependency on that flag.

**Review by jin — APPROVED** [review]

**Comment by shs96c** [comment]
To show this in action:

```shell
git clone https://github.com/bazelbuild/rules_jvm_external.git
git clone https://github.com/bazel-contrib/rules_jvm.git
cd rules_jvm
bazel build //... --override_module=$(pwd)/../rules_jvm_external
```

With the `rules_android` update in place, this will fail. Without it, the build will succeed.

**Comment by ahumesky** [comment]
Sorry for the trouble, `@rules_android//rules/reexport_providers.bzl` is actually a part of removing the need for `--experimental_google_legacy_api` and was added after starting on https://github.com/bazelbuild/rules_jvm_external/commit/ba7310ce4a1d8fb14434597fbc7440a4074f7695, didn't realize this would require projects not using the android rules to add the flag.

**Comment by shs96c** [comment]
It happens, and I'm surprised it managed to slip through all the tests and checks. We know now, and we can fix things. Genuinely looking forwards to the time we can roll this forward again. Thank you for all your work making that happen!

**Comment by ahumesky** [comment]
We've made significant progress on https://github.com/bazelbuild/rules_android/issues/256 / https://github.com/bazelbuild/rules_android/issues/219 Maybe this week or next we can try again with an updated version of https://github.com/bazelbuild/rules_jvm_external/commit/ba7310ce4a1d8fb14434597fbc7440a4074f7695 + updated version of rules_android

**Comment by shs96c** [comment]
I'd be happy to try it. Would be great to land this properly :)

**Comment by ahumesky** [comment]
With bazel 7.4.0rc1 created today, I tested reapplying `7b4512b24303737dd5ba53d53d94ff9c5e4e6320` and using the latest rules_android, and this all seems to work now with either `--experimental_google_legacy_api` / `--experimental_enable_android_migration_apis`:

```
~/rules_jvm$ USE_BAZEL_VERSION=7.4.0rc1 bazelisk build //... --override_module=rules_jvm_external=$(pwd)/../rules_jvm_external --override_module=rules_android=$(pwd)/../rules_android

......

INFO: Found 256 targets...
INFO: Elapsed time: 45.499s, Critical Path: 41.73s
INFO: 2318 processes: 1013 internal, 1237 linux-sandbox, 68 worker.
INFO: Build completed successfully, 2318 total actions
```

**Comment by ahumesky** [comment]
We've been working to create rules_android version 0.6.0 this week and last, when that's out I'll to get all this committed again

**Comment by ahumesky** [comment]
Since we're getting close(r) to a 0.6.0 release of rules_android, I tried my PR again with rules_android at head, and get some new errors.

It looks like there are conflicting definitions of `@maven` from multiple places:
```
DEBUG: /usr/local/google/home/ahumesky/rules_jvm_external/private/extensions/maven.bzl:155:14: The maven repository 'maven' is used in two different bazel modules, originally in 'rules_jvm_external' and now in 'protobuf'
DEBUG: /usr/local/google/home/ahumesky/rules_jvm_external/private/extensions/maven.bzl:155:14: The maven repository 'multiple_lock_files' is used in two different bazel modules, originally in 'rules_jvm_external' and now in 'bzlmod_lock_files'
DEBUG: /usr/local/google/home/ahumesky/rules_jvm_external/private/extensions/maven.bzl:155:14: The maven repository 'maven' is used in two different bazel modules, originally in 'rules_jvm_external' and now in 'bazel_worker_java'
DEBUG: /usr/local/google/home/ahumesky/rules_jvm_external/private/extensions/maven.bzl:155:14: The maven repository 'maven' is used in two different bazel modules, originally in 'rules_jvm_external' and now in 'bazel_worker_java'
DEBUG: /usr/local/google/home/ahumesky/rules_jvm_external/private/extensions/maven.bzl:155:14: The maven repository 'maven' is used in two different bazel modules, originally in 'rules_jvm_external' and now in 'bazel_worker_java'
DEBUG: /usr/local/google/home/ahumesky/rules_jvm_external/private/extensions/maven.bzl:155:14: The maven repository 'maven' is used in two different bazel modules, originally in 'rules_jvm_external' and now in 'bazel_worker_java'
```

leading to (at least):
```
ERROR: /usr/local/google/home/ahumesky/.cache/bazel/_bazel_ahumesky/47f161388952f98f7ec077017d030a4d/external/_main~maven~maven/BUILD: no such target '@@_main~maven~maven//:com_google_protobuf_protobuf_java': target 'com_google_protobuf_protobuf_java' not declared in package '' defined by /usr/local/google/home/ahumesky/.cache/bazel/_bazel_ahumesky/47f161388952f98f7ec077017d030a4d/external/_main~maven~maven/BUILD
ERROR: /usr/local/google/home/ahumesky/.cache/bazel/_bazel_ahumesky/47f161388952f98f7ec077017d030a4d/external/bazel_worker_java~/src/main/java/com/google/devtools/build/lib/worker/BUILD.bazel:5:13: no such target '@@_main~maven~maven//:com_google_protobuf_protobuf_java': target 'com_google_protobuf_protobuf_java' not declared in package '' defined by /usr/local/google/home/ahumesky/.cache/bazel/_bazel_ahumesky/47f161388952f98f7ec077017d030a4d/external/_main~maven~maven/BUILD and referenced by '@@bazel_worker_java~//src/main/java/com/google/devtools/build/lib/worker:work_request_handlers'
```

**Comment by ahumesky** [comment]
Looks like there are some comments about the `'maven' is used in two different bazel modules` issue above here: https://github.com/bazel-contrib/rules_jvm_external/blob/534e62d14655e01048b90ef89ab1acaf0caa7348/MODULE.bazel#L152-L156

Latest rules_android needs to use the latest protobuf, so the android test targets (e.g. `//tests/integration/override_targets:override_targets`) in rules_jvm_external will start to fail

**Comment by ahumesky** [comment]
This seems to avoid the `@maven` conflicts between `bazel_worker_java` and `rules_jvm_external`: https://github.com/bazelbuild/bazel-worker-api/pull/8

**Comment by ahumesky** [comment]
Regarding https://github.com/bazel-contrib/rules_jvm_external/pull/1215#issuecomment-2533261865 apparently I just needed to do `REPIN=1 bazel run @maven//:pin`

**Comment by ahumesky** [comment]
I can get `rules_android` at head + `rules_jvm_external` at head + reapplying my change https://github.com/bazel-contrib/rules_jvm_external/commit/ba7310ce4a1d8fb14434597fbc7440a4074f7695 (at https://github.com/bazel-contrib/rules_jvm_external/pull/1296) working with {bazel 8.0.0, bazel 7.4.1} x {bzlmod, workspace}.

When I try bazel 6.5.0 with bzlmod, I get
```
ERROR: @@rules_jvm_external~override//:MODULE.bazel:110:13: name 'use_repo_rule' is not defined
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> rules_jvm_external@_: error executing MODULE.bazel file for rules_jvm_external@_
```
So it looks like rules_jvm_external at head doesn't work with bazel 6.5.0 + bzlmod

When I try it with workspace, I get a lot of problem with rules_android requiring things that aren't in bazel 6.5.0 (configuration fields, some things in `@bazel_toosl`, etc). I can get rules_jvm_external at head + my change above working with the native Android rules however, which are still in bazel 6 and bazel 7. So I think it would be the best course to run any tests in rules_jvm_external that use bazel 6 with the native Android rules.

**Comment by jin** [comment]
> So it looks like rules_jvm_external at head doesn't work with bazel 6.5.0 + bzlmod

This is fine. rules_jvm_external only supports bzlmod with Bazel 7+, not 6.5.0. We only support WORKSPACE with Bazel 6.5.0.

> So I think it would be the best course to run any tests in rules_jvm_external that use bazel 6 with the native Android rules.

This works.

**Pull request merged**
