### PR TITLE
Bump Robolectric to 4.8.1

### PR DESCRIPTION
**Pull request by utzcoz**
See https://github.com/robolectric/robolectric-bazel/releases/tag/4.8.1 and https://github.com/robolectric/robolectric/releases/tag/robolectric-4.8.1.

### CODE REVIEW

**Comment by utzcoz** [comment]
cc @Bencodes

**Review by Bencodes — APPROVED** [review]
Thanks for updating this!

**Comment by utzcoz** [comment]
Hi @jin , could you help to review this PR? Thanks.

**Review by jin — APPROVED** [review]

**Comment by jin** [comment]
thanks!

**Pull request merged**
