### PR TITLE
update bazel skylib and use rbe_preconfig

### PR DESCRIPTION
**Pull request by aranguyen**
[update bazel skylib and use rbe_preconfig](https://github.com/bazelbuild/rules_jvm_external/commit/ac8dd71039e56bf24bdc14672addaaac8973a486) https://github.com/bazelbuild/continuous-integration/issues/1404

### CODE REVIEW

**Comment by aranguyen** [comment]
@cheister could you please take a look at this at the earliest of your convenience? We're trying to get the flag flip for 6.0

**Comment by meteorcloudy** [comment]
@shs96c Can you help merging this? This will enable us to flip https://github.com/bazelbuild/bazel/issues/8622

**Review by shs96c — APPROVED** [review]
LGTM, though I'm unsure why the kotlin tests were changed in this PR.

**Comment by meteorcloudy** [comment]
@aranguyen Is the kotlin test change really necessary in this PR?

**Comment by aranguyen** [comment]
@meteorcloudy re-testing it now. I remember seeing the error related to this in my local build -> hence the change.

**Pull request merged**
