### PR TITLE
Remove references to jcenter.bintray.com which is being shutdown on May 1, 2021

### PR DESCRIPTION
**Pull request by cheister**
Fix for https://github.com/bazelbuild/rules_jvm_external/issues/517

### CODE REVIEW

**Review by jin — APPROVED** [review]

**Comment by cheister** [comment]
@jin Looks like `//tests/com/jvm/external:UnsafeSharedCacheTest` is failing on OSX.  I'm not sure if https://github.com/bazelbuild/rules_jvm_external/issues/375 is now a problem for OSX as well and if `//tests/com/jvm/external:UnsafeSharedCacheTest"` should be commented out for OSX in `.bazelci/presubmit.yml` as well?

**Comment by jin** [comment]
The failure is 

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tests/com/jvm/external:UnsafeSharedCacheTest
-----------------------------------------------------------------------------
JUnit4 Test Runner
.E
Time: 0.031
There was 1 failure:
1) test_jarsOnClassPath_areInTheSharedCache(com.jvm.external.UnsafeSharedCacheTest)
java.lang.AssertionError: 
Expected: a string containing "/tmp/custom_coursier_cache"
     but: was "file:/private/var/tmp/_bazel_buildkite/0f1ff3967c5ac2afc60797312589b600/execroot/rules_jvm_external/bazel-out/darwin-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/hamcrest/hamcrest/2.1/processed_hamcrest-2.1.jar"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at com.jvm.external.UnsafeSharedCacheTest.test_jarsOnClassPath_areInTheSharedCache(UnsafeSharedCacheTest.java:35)

FAILURES!!!
Tests run: 1,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2021-02-16 07:45:59 --
```

which is different from the linked issue. I think this has something to do with a recent mac upgrade on CI. Looking.

**Comment by jin** [comment]
Could you try changing this line:

https://github.com/bazelbuild/rules_jvm_external/blob/367eb9ae5be8acd5a069b84c4672a2ed1d0bda82/.bazelci/presubmit.yml#L79

as well as UnsafeSharedCacheTest itself to use /Users/buildkite/coursier_cache, instead of the /tmp dir? I'm guessing that something stateful happened in the CI upgrade that caused something odd with /tmp.

**Comment by cheister** [comment]
Ok, sorted it out the UnsafeSharedCacheTest was only working before because of a typo in the test looking for `jcentray.bintray.com` instead of `jcenter.bintray.com`, this filtered out the hamcrest dependencies.  Since only the `guava` dependency is included in https://github.com/bazelbuild/rules_jvm_external/blob/master/tests/integration/BUILD#L66, that is the only one we should look for in the test with the coursier_cache path.

**Comment by jin** [comment]
Yikes, good catch.

**Pull request merged**
