### PR TITLE
Split presubmit.yml into test targets and examples

### PR DESCRIPTION
**Pull request by jin**
The `tasks` and `platforms` blocks need to be in separate files, and we'll have to create a new Buildkite pipeline for the examples.

### CODE REVIEW

**Comment by dkelmer** [comment]
Does this mean only the tasks in presubmit.yml will get run on presubmit? When will the examples.yml tasks get built/tested?

**Comment by jin** [comment]
The filenames don't actually matter. I'll need to make a new Buildkite pipeline for examples.yml.

**Comment by jin** [comment]
We don't really have a postsubmit, since presubmit covers the same set of targets.

**Comment by dkelmer** [comment]
So the idea is that both of the buildkite pipelines will be triggered on
presubmit?

**Comment by jin** [comment]
Yup!

**Pull request merged**
