### PR TITLE
(example): add scala akka http application.

### PR DESCRIPTION
**Pull request by dgarzon**
This PR adds and example of a fairly complex Scala application, and how to use the rules to successfully build / run / test it. In comparison to `bazel-deps`, we now need to define extra `deps` in order for `rules_scala` to pick them up. No big deal! @jin awesome job on this project!

### CODE REVIEW

**Comment by dgarzon** [comment]
I signed it!

**Comment by jin** [comment]
Nice, thank you! Do you mind adding some entries to the CI config for the build and test targets, like the ones for the Spring Boot application?

https://github.com/bazelbuild/rules_jvm_external/blob/40d2e50d7d140eea39b353709854a26b7a870cd4/.bazelci/examples.yml#L84

Feel free to add it for all three platforms; we can delete them if they fail on postsubmit later.

**Comment by jin** [comment]
also, can you rename the example directory from `scala` to `scala_akka`? So it's clearer that it's an Akka application from browsing the file tree.

**Comment by dgarzon** [comment]
Will do @jin . Will push once I address all your comments! Thank you for the review ❤️

**Pull request merged**
