### PR TITLE
Automatically generate a netrc file according to basic http auth in url

### PR DESCRIPTION
**Pull request by justhecuke**
For every mirror url in a pinned json, try to extract netrc credentials. Then, write those credentials into a file that every generated http_file for the various maven artifacts will use.

Alternative way of implementing would be by allowing you to pass a pre-made netrc and that can be added in later if we should choose to do so, although it may be somewhat difficult to do so due to there being at least three different repositories in play making it difficult to use raw paths.

With this change, basic http auth will appear to be supported even though it technically isn't since we are translating basic http auth into netrc auth with all of netrc's shortcomings.

In the majority of cases I expect for this to be enough, but for complex auth schemes we may need something in addition.

Fixes https://github.com/bazelbuild/rules_jvm_external/issues/186

### CODE REVIEW

**Comment by justhecuke** [comment]
Hmm, seems like I need to fix this for bazel 25.3.

**Comment by jin** [comment]
Wow, awesome! I'll make a deeper review ASAP, but feel free to ignore the failing tests before 0.27.2, since netrc wasn't added before then. It's about time we release a new major version that only works with 1.x.

**Comment by jin** [comment]
Could you please rebase to https://github.com/bazelbuild/rules_jvm_external/commit/a62917b62833aa5d5ac5e1451fdb0f29d92545d5?

**Comment by joprice** [comment]
It seems that this broke the default behavior where the netrc in the home directory is used https://github.com/bazelbuild/bazel/blob/e9bef0cf46a71039e45f797c98acc201e13ae602/tools/build_defs/repo/http.bzl#L52. 

Filtering out empty netrc dicts works for me:  https://github.com/bazelbuild/rules_jvm_external/compare/master...joprice:emptyNetrc, but I can image someone might expect the two sources to be merged instead.

**Comment by justhecuke** [comment]
> It seems that this broke the default behavior where the netrc in the home directory is used https://github.com/bazelbuild/bazel/blob/e9bef0cf46a71039e45f797c98acc201e13ae602/tools/build_defs/repo/http.bzl#L52.
> 
> Filtering out empty netrc dicts works for me: [master...joprice:emptyNetrc](https://github.com/bazelbuild/rules_jvm_external/compare/master...joprice:emptyNetrc), but I can image someone might expect the two sources to be merged instead.

That would make a lot of sense. Sorry for missing this use-case. My team is leery of using non-repo netrc because it breaks hermeticity. I'll see what I can do to fix.

**Comment by joprice** [comment]
I was curious about the workflow that this supports. Do you check credentials into the WORKSPACE file? Our use of netrc was to avoid doing that.

**Comment by jin** [comment]
This adds support for the inlined auth params, and technically the auth params don't need to be in the WORKSPACE -- they can be loaded from a .bzl that's not checked in. 

Since Bazel supports reading ~/.netrc, we should find a way to combine both files.

**Comment by justhecuke** [comment]
We have actually checked-in our credentials but I'm led to believe that this is more for usage-tracking rather than real security. The server we are authing into is in our VPN and is mostly a cache for other maven repos to decrease latency and increase bandwidth.

We also use a generated `.bzl` that we create in a bazel wrapper that is used by the WORKSPACE so that we can keep different systems in sync. We are currently moving to bazel and are concurrently supporting multiple build systems.

**Comment by joprice** [comment]
I'm not a heavy user of netrc, only found it useful recently because of tools like curl supporting it. I can try the non-checked in bazel file. And I like the idea of having some bootstrap task to generate it. Would this be the encouraged approach either way so that changing credentials invalidates the existing cache?

**Comment by justhecuke** [comment]
@joprice https://github.com/bazelbuild/rules_jvm_external/pull/319

Is this something that you can try to see if it works for you? I haven't set up a local test yet and I wanted to make sure that your use-case was addressed.

**Pull request merged**
