### PR TITLE
Remove "jetify" functionality

### PR DESCRIPTION
**Pull request by shs96c**
This has been deprecated for a while, and the list of dependencies that required jetifying is old. It is hoped that people will have updated their own dependencies by now, rather than requiring this tooling to handle that case.

### CODE REVIEW

**Comment by cheister** [comment]
Seems fine, just need to get the last tests passing
```
Error: file '//private:dependency_tree_parser.bzl' does not contain symbol 'JETIFY_INCLUDE_LIST_JETIFY_ALL'
```

**Comment by cheister** [comment]
Is the plan to merge this PR before https://github.com/bazelbuild/rules_jvm_external/pull/967 ?

**Comment by shs96c** [comment]
Yes, I think it makes sense to get this in before #967.

**Comment by shs96c** [comment]
@cheister, this is ready for review again

**Pull request merged**
