### PR TITLE
Bump coursier to v2.1.0-RC2

### PR DESCRIPTION
**Pull request by jin**
Also mirrored to https://mirror.bazel.build/coursier_cli/coursier_cli_v2.1.0-RC2.jar

### CODE REVIEW

**Review by shs96c — APPROVED** [review]
LGTM, though it's interesting that the lock files have changed.

**Comment by jin** [comment]
I downloaded zookeeper-3.4.13 and verified that the new lock files reflects the deps in its pom file. Given that there's nothing stopping Maven owners from changing POM files for released artifacts, it'd explain changed lock files like these.

**Comment by cheister** [comment]
LGTM, thanks for the update

**Comment by shs96c** [comment]
The lock file is generated by serialising the `artifacts` from `maven_install` (in the common case, that's just a regular GAV tuple) and passing them to `coursier`. In this case, it looks like `io.opencensus:opencensus-api:0.24.0` did something interesting: it went from including `io.grpc:grpc-context:1.33.1` as a dependency to adding it to the `exclusions`.

**Pull request merged**
