### PR TITLE
Append srcjar to aar_import

### PR DESCRIPTION
**Pull request by Bencodes**
Appending the srcjar when available to the `aar_import`.

### CODE REVIEW

**Comment by jin** [comment]
It would be nice to have an integration test (like the ones in the WORKSPACE file) that depends on an AAR that will trigger this codepath - could you add a test like that?

**Comment by Bencodes** [comment]
I'll take a look at adding a quick test this week.

**Comment by Bencodes** [comment]
@jin the PR has been updated with some tests.

**Comment by jin** [comment]
```
Oct 04, 2021 3:02:00 AM com.google.devtools.build.android.AndroidCompiledResourceMergingAction main
--
  | SEVERE: Error during merging resources
  | com.google.devtools.build.android.AndroidResourceMerger$MergingException: Error during merging
  | at com.google.devtools.build.android.AndroidResourceMerger$MergingException.wrapException(AndroidResourceMerger.java:75)
  | at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:283)
  | at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
  | at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
  | at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
  | at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
  | Caused by: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: lStar
  | at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:122)
  | at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
  | at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:275)
  | ... 4 more
  | Caused by: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: lStar
  | at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrId(AndroidFrameworkAttrIdJar.java:48)
  | at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:329)
  | at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:238)
  | at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:114)
  | ... 6 more
  |  
  | Oct 04, 2021 3:02:00 AM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
```

The line is `Android attribute not found: lStar` - is there an issue with this particular artifact?

**Comment by Bencodes** [comment]
@jin updated with a simpler artifact. One of the jobs needs to be retried but everything else looks good.

**Review by jin — APPROVED** [review]
Thank you!

**Pull request merged**
