### PR TITLE
De-duplicate dependency tree in the json output file before using it

### LINKED ISSUE #311: "Could not create symlink" when using use_unsafe_shared_cache = True
When activating the `use_unsafe_shared_cache` setting, I see the error below:

```
'@scala_2_11//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_adamjohnson/09e8271e29391b7bad9dc3e7f8bde013/external/rules_jvm_external/coursier.bzl", line 503
		artifact.update(<1 more arguments>)
	File "/private/var/tmp/_bazel_adamjohnson/09e8271e29391b7bad9dc3e7f8bde013/external/rules_jvm_external/coursier.bzl", line 503, in artifact.update
		_relativize_and_symlink_file(<2 more arguments>)
	File "/private/var/tmp/_bazel_adamjohnson/09e8271e29391b7bad9dc3e7f8bde013/external/rules_jvm_external/coursier.bzl", line 69, in _relativize_and_symlink_file
		repository_ctx.symlink(<2 more arguments>)
java.io.IOException: Could not create symlink from /Users/adamjohnson/Library/Caches/Coursier/v1/http/localhost%3A8080/iheart/amp-bazel-external/com/fasterxml/jackson/core/jackson-databind/2.7.8/jackson-databind-2.7.8.jar to /private/var/tmp/_bazel_adamjohnson/09e8271e29391b7bad9dc3e7f8bde013/external/scala_2_11/v1/http/localhost%3A8080/iheart/amp-bazel-external/com/fasterxml/jackson/core/jackson-databind/2.7.8/jackson-databind-2.7.8.jar: /private/var/tmp/_bazel_adamjohnson/09e8271e29391b7bad9dc3e7f8bde013/external/scala_2_11/v1/http/localhost%3A8080/iheart/amp-bazel-external/com/fasterxml/jackson/core/jackson-databind/2.7.8/jackson-databind-2.7.8.jar (File exists)
```

I have tried deleting the cache and re-running and get the same error.

### PR DESCRIPTION
**Pull request by jin**
Coursier can produce duplicate artifact entries in its JSON output file. Short of fixing it upstream, we run a deduplication before using it. 

Fixes #311

### CODE REVIEW

**Comment by gergelyfabian** [comment]
There is still one possible issue with duplicates.
De-duplication is done basing on artifact["coord"], however I have a case when "coord" is different for two files in the coursier output, but the generated file name is identical (and thus symlinking fails)
For this case #311 is unsolved.

Example:
"coord": "groupid:artifactid:jar:sources:1.0.0", "file": ".../artifactid-1.0.0-sources.jar"
"coord": "groupid:artifactid:test-jar:sources:1.0.0", "file": ".../artifactid-1.0.0-sources.jar"

Could the deduplication somehow cover for this case?

**Comment by jin** [comment]
Thanks, @gergelyfabian! Could you please follow the instructions in https://github.com/bazelbuild/rules_jvm_external/pull/327#issuecomment-566188517 to make the cla bot happy?

**Comment by jin** [comment]
Hi @gergelyfabian could you please leave a comment containing just `@googlebot I consent.`? I am unable to merge this PR otherwise.

**Comment by gergelyfabian** [comment]
@googlebot I consent

**Comment by gergelyfabian** [comment]
> Hi @gergelyfabian could you please leave a comment containing just `@googlebot I consent.`? I am unable to merge this PR otherwise.

I just left the comment. You should be good to go :)
Sorry, did not see the notification earlier.

**Comment by jin** [comment]
Awesome, thank you.

**Pull request merged**
