### PR TITLE
Update to latest rules_kotlin

### PR DESCRIPTION
**Pull request by sgowroji**
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/946

### CODE REVIEW

**Comment by shs96c** [comment]
Thank you for the PR. Updating to the latest release would be great.

It looks like there are genuine failures with this PR:

```shell
tests/bazel_run_tests.sh
--
  | ERROR: Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_bazel_rules_kotlin/kotlin/internal/defs.bzl", line 23, column 25, in <toplevel>
  | JavaPluginInfo = getattr(java_common, "JavaPluginInfo")
  | Error in getattr: 'java_common' value has no field or method 'JavaPluginInfo'
  | ERROR: error loading package '': in /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_bazel_rules_kotlin/kotlin/repositories.bzl: in /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl: Extension file 'kotlin/internal/defs.bzl' has errors
  | INFO: Elapsed time: 2.154s
  | INFO: 0 processes.
```

from [here](https://buildkite.com/bazel/rules-jvm-external/builds/3576#018a457a-2731-46ba-9b7b-78139e0ed8da)

**Comment by sgowroji** [comment]
Closing this one. I will update once after getting complete information.

**Comment by sgowroji** [comment]
@hvadehra Could you please guide on the failures. Thanks!

**Comment by hvadehra** [comment]
The failure linked above is for builds using Bazel 4.x. which presumably the kotlin rules no longer support. The bazel team itself is dropping support for v4 in a few months: https://bazel.build/release#support-matrix 

The failure for bazel 5.0 is a little surprising, looking into it now.

**Comment by hvadehra** [comment]
Okay, so I can reproduce the failure for 5.0.0 locally, but tests pass with 5.4.1 which is the version everyone on 5.x should be using.

**Comment by shs96c** [comment]
@jin, do you think it's fine for us to require the last 5.x release? Or should we hold off on this?

**Comment by jin** [comment]
If Bazel 4's going to be EOL soon, I think it's reasonable to start requiring 5.X for the next RJE release.

**Comment by sgowroji** [comment]
Closing this PR as this doesn't fix the above issue. Thanks.

**Pull request closed without merging**
