### PR TITLE
Add support for m2Local repository

### PR DESCRIPTION
**Pull request by tokudu**
This PR addresses the following open issues:
https://github.com/bazelbuild/rules_jvm_external/issues/522
https://github.com/bazelbuild/rules_jvm_external/issues/305

Coursier supports passing `m2Local` in the list of repositories, but jvm external can't properly handle the dependency tree output, since it returns pointers to the original files within `~/.m2/repository` directory. 

Sample usage (you probably have to add `fail_on_missing_checksum`, since mavel local is likely missing checksums:
```
    maven_install(
        name = "maven",
        artifacts = [ 
             ...
        ],
        repositories = [
            "m2Local"
        ],
        fail_on_missing_checksum = True
    )
```

### CODE REVIEW

**Comment by jin** [comment]
Thanks for working on this! Nice to see that it actually works with Coursier support. Could you please add some tests, especially integration tests? I would be more comfortable accepting this with its code path tested. You may need to modify .bazelci/presubmit.yml to run some setup script to pre-populate a local .m2 repository for those integration tests as well.

**Comment by tokudu** [comment]
Will do. This needs to be cleaned up a bit to support the pinned maven_install.json path. Still doing some more testing.

**Comment by tokudu** [comment]
Ok both pinned and unpinned cases should be working now. Will follow up next week with some integration tests

**Comment by kamildoleglo** [comment]
Hi! Are there any updates on this? ☺️

**Comment by tokudu** [comment]
I haven't had the time to add the integration tests as it ended up being pretty convoluted, but we have been using for a while in our internal fork and it works well.

**Comment by tokudu** [comment]
You are welcome to contribute and we can team up to get this over the finish line.

**Comment by smocherla-brex** [comment]
@tokudu I'd like to take a stab at getting this merged, if that's ok with you?

**Comment by tokudu** [comment]
Absolutely!

**Comment by jin** [comment]
#695 has been merged. Thanks all!

**Comment by tjbanghart** [comment]
Hey yall glad to see this! I haven't been able to get this to work for my purposes though and could use a reality check.

I have a gradle project I am publishing to my maven local repo via [Maven Publish Plugin](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:install) 

In my bazel project I am pulling in maven dependencies with the following helper:

```
def _maven_pinned_nexus_install(name, artifacts = [], excluded_artifacts = []):
    maven_install(
        name = name,
        artifacts = artifacts,
        repositories = [
            "https://nexusrepo.<my_proxy>.com/repository/maven-public/",
            "m2Local"
        ],
        fail_if_repin_required = True,
        fail_on_missing_checksum = False,
        fetch_sources = False,
        maven_install_json = "//internal/repositories:%s_install.json" % name,
        strict_visibility = False,
        version_conflict_policy = "pinned",
        excluded_artifacts = excluded_artifacts,
    )

```

While repining I get the following error:
```
invalid label '/usr/local/tjbanghart/.m2/<path_to_jar>' in element 0 of attribute 'jars' in 'jvm_import' rule: invalid target name '/usr/local/tjbanghart/.m2/<path_to_jar>': target names may not start with '/'
```
Is `m2Local` only compatible with certain types of artifacts? It seems like the `file://` target prefix  is missing? Any ideas are welcome. Thank you 🙇

**Comment by smocherla-brex** [comment]
@tjbanghart It would seem that m2Local absolute path isn't converted to a relative path and symlinked as it should be [here](https://github.com/bazelbuild/rules_jvm_external/blob/master/coursier.bzl#L1014). I can't personally reproduce it myself, but if you have a simple repro, I could take a look.

If you could also perhaps share the output of this 
```
bazel query @unpinned_maven//... --output=build
```
that might also be more clarifying as to what's going wrong.

**Pull request closed without merging**
