### PR TITLE
Output actual command line when using RJE_VERBOSE

### PR DESCRIPTION
**Pull request by cheister**
Often when I use RJE_VERBOSE I want to see the actual commands getting executed.  

This PR adds a wrapper method around repository_ctx.execute to output the command getting run before running the command when RJE_VERBOSE is true.

### CODE REVIEW

**Comment by jin** [comment]
Is there a particular reason you chose `echo` over the regular `print()` function?

Also, would it be useful to add an optional `report_progress` call into the `_execute` function while we're at it?

**Comment by cheister** [comment]
I started with a regular `print()` function but it doesn't get output to the terminal.

For the `report_progress` are you thinking that `_execute` should take an optional parameter for a progress message and call `repository_ctx.report_progress` with it?

**Comment by jin** [comment]
Replacing it with `print()` works for me:

```
...
DEBUG: /usr/local/google/home/jingwen/code/rules_jvm_external/coursier.bzl:105:14: [/usr/local/buildtools/java/jdk8/bin/java, "-noverify", "-jar", /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8484bc4fff18ee4a905b69a9ddb0e143/external/starlark_aar_import_with_jetify_test/coursier, "fetch", "com.android.support:appcompat-v7:28.0.0", "--artifact-type", "jar,json,aar,bundle,eclipse-plugin,orbit,test-jar,hk2-jar,maven-plugin,scala-jar,src,doc", "--verbose", "--no-default", "--json-output-file", "dep-tree.json", "--checksum", "SHA-1,MD5", "--repository", "https://jcenter.bintray.com/", "--repository", "https://maven.google.com", "--cache", "v1"]
DEBUG: /usr/local/google/home/jingwen/code/rules_jvm_external/coursier.bzl:105:14: [/usr/local/buildtools/java/jdk8/bin/java, "-noverify", "-jar", /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8484bc4fff18ee4a905b69a9ddb0e143/external/starlark_aar_import_with_jetify_test/coursier, "fetch", "androidx.arch.core:core-common:2.0.0", "androidx.arch.core:core-runtime:2.0.0", "androidx.lifecycle:lifecycle-common:2.0.0", "androidx.lifecycle:lifecycle-livedata-core:2.0.0", "androidx.lifecycle:lifecycle-livedata:2.0.0", "androidx.lifecycle:lifecycle-runtime:2.0.0", "androidx.lifecycle:lifecycle-viewmodel:2.0.0", "androidx.vectordrawable:vectordrawable-animated:1.0.0", "androidx.appcompat:appcompat:1.0.0", "androidx.asynclayoutinflater:asynclayoutinflater:1.0.0", "androidx.collection:collection:1.0.0", "androidx.coordinatorlayout:coordinatorlayout:1.0.0", "androidx.cursoradapter:cursoradapter:1.0.0", "androidx.customview:customview:1.0.0", "androidx.documentfile:documentfile:1.0.0", "androidx.drawerlayout:drawerlayout:1.0.0", "androidx.interpolator:interpolator:1.0.0", "androidx.loader:loader:1.0.0", "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0", "androidx.print:print:1.0.0", "androidx.slidingpanelayout:slidingpanelayout:1.0.0", "androidx.annotation:annotation:1.0.0", "androidx.core:core:1.0.0", "androidx.legacy:legacy-support-core-ui:1.0.0", "androidx.legacy:legacy-support-core-utils:1.0.0", "androidx.fragment:fragment:1.0.0", "androidx.vectordrawable:vectordrawable:1.0.0", "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0", "androidx.versionedparcelable:versionedparcelable:1.0.0", "androidx.viewpager:viewpager:1.0.0", "com.android.support:appcompat-v7:28.0.0", "--artifact-type", "jar,json,aar,bundle,eclipse-plugin,orbit,test-jar,hk2-jar,maven-plugin,scala-jar,src,doc", "--verbose", "--no-default", "--json-output-file", "dep-tree.json", "--checksum", "SHA-1,MD5", "--repository", "https://jcenter.bintray.com/", "--repository", "https://maven.google.com", "--cache", "v1"]
...
```

**Comment by cheister** [comment]
Ah, I see. I was testing with a large dependency set and using `print()` means the command line output gets output after all of the coursier output has been run so I wasn't looking for it after all of the coursier output. 

e.g. using print() gives
```
> RJE_VERBOSE=true bazel run @maven//:pin          
Coursier 2.0.7
Usage: coursier [options] [command] [command-options]

Available commands: bootstrap, channel, complete, fetch, get, install, java, java-home, launch, list, publish, resolve, setup, uninstall, update

Type  coursier command --help  for help on an individual command
  Dependencies:
com.fasterxml.jackson.core:jackson-annotations:2.12.1:
  Force versions:
com.fasterxml.jackson.core:jackson-annotations:2.12.1
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/oss-parent/41/oss-parent-41.pom
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/oss-parent/41/oss-parent-41.pom
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar
v1/https/repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar
v1/https/repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar
203cefdfa6c81e6aa84e11f292f29ca97344a3c3bc0293abea065cd837592873 /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/v1/https/repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar
e7d07607cf333d0412c97d60bc956627b0966ffd304f2323ee3aba0d6d6c96de /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/v1/https/repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar
DEBUG: /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/rules_jvm_external/coursier.bzl:105:14: 
/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/bin/java -noverify -jar /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/coursier --help
DEBUG: /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/rules_jvm_external/coursier.bzl:105:14: 
/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/bin/java -noverify -jar /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/coursier fetch com.fasterxml.jackson.core:jackson-annotations:2.12.1 --force-version com.fasterxml.jackson.core:jackson-annotations:2.12.1 --artifact-type jar,json,aar,bundle,eclipse-plugin,orbit,test-jar,hk2-jar,maven-plugin,scala-jar,src,doc --verbose --no-default --json-output-file dep-tree.json --checksum SHA-1,MD5 --repository https://repo.maven.apache.org/maven2/ --repository https://mvnrepository.com/artifact --repository https://maven-central.storage.googleapis.com --repository http://gitblit.github.io/gitblit-maven --repository https://repository.mulesoft.org/nexus/content/repositories/public/ --sources --default=true --cache v1
DEBUG: /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/rules_jvm_external/coursier.bzl:105:14: 
/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/bin/java -noverify -jar /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/rules_jvm_external/private/tools/prebuilt/hasher_deploy.jar --argsfile /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/hasher_argsfile
INFO: Analyzed target @maven//:pin (4 packages loaded, 9 targets configured).
INFO: Found 1 target...
Target @maven//:pin up-to-date:
  bazel-bin/external/maven/pin
INFO: Elapsed time: 5.006s, Critical Path: 0.00s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
```

and using echo gives

```
> RJE_VERBOSE=true bazel run @maven//:pin 

/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/bin/java -noverify -jar /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/coursier --help
Coursier 2.0.7
Usage: coursier [options] [command] [command-options]

Available commands: bootstrap, channel, complete, fetch, get, install, java, java-home, launch, list, publish, resolve, setup, uninstall, update

Type  coursier command --help  for help on an individual command

/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/bin/java -noverify -jar /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/coursier fetch com.fasterxml.jackson.core:jackson-annotations:2.12.1 --force-version com.fasterxml.jackson.core:jackson-annotations:2.12.1 --artifact-type jar,json,aar,bundle,eclipse-plugin,orbit,test-jar,hk2-jar,maven-plugin,scala-jar,src,doc --verbose --no-default --json-output-file dep-tree.json --checksum SHA-1,MD5 --repository https://repo.maven.apache.org/maven2/ --repository https://mvnrepository.com/artifact --repository https://maven-central.storage.googleapis.com --repository http://gitblit.github.io/gitblit-maven --repository https://repository.mulesoft.org/nexus/content/repositories/public/ --sources --default=true --cache v1
  Dependencies:
com.fasterxml.jackson.core:jackson-annotations:2.12.1:
  Force versions:
com.fasterxml.jackson.core:jackson-annotations:2.12.1
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/oss-parent/41/oss-parent-41.pom
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/oss-parent/41/oss-parent-41.pom
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar
Downloading https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar
Downloaded https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar
v1/https/repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar
v1/https/repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar

/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home/bin/java -noverify -jar /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/rules_jvm_external/private/tools/prebuilt/hasher_deploy.jar --argsfile /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/hasher_argsfile
203cefdfa6c81e6aa84e11f292f29ca97344a3c3bc0293abea065cd837592873 /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/v1/https/repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar
e7d07607cf333d0412c97d60bc956627b0966ffd304f2323ee3aba0d6d6c96de /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/maven/v1/https/repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar
INFO: Analyzed target @maven//:pin (4 packages loaded, 9 targets configured).
INFO: Found 1 target...
Target @maven//:pin up-to-date:
  bazel-bin/external/maven/pin
INFO: Elapsed time: 5.167s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
```

It seems better to use echo since it matches the output where the command is called and doesn't have the `DEBUG: /private/var/tmp/_bazel_cheister/60fd9b2f4bf06a7f576b88fee484f3ad/external/rules_jvm_external/coursier.bzl:105:14:`prefix in the log message, so it feels more connected to the output from the command.

**Review by jin — APPROVED** [review]

**Comment by jin** [comment]
Ah, thanks for that output! Agree that it looks much better with echo here. LGTM

**Pull request merged**
