### PR TITLE
rules_jvm_external_deps: add possibility to override params used for maven install

### PR DESCRIPTION
**Pull request by gergelyfabian**
…maven_install

### CODE REVIEW

**Comment by shs96c** [comment]
I'm wondering what the motivation for this PR is. The deps linked to are internal to `rules_jvm_external`, and we don't expect people to be relying or modifying them. I'm not sure why we'd want to allow people to change these values.

The two cases I can think of:

1. Someone is patching `rules_jvm_external`, at which point their patch can also modify the lock file.
2. Someone is attempting to rely on dependencies brought in transitively from these deps, which isn't something we want to encourage.

However, it's entirely possible I've missed something obvious :)

**Comment by gergelyfabian** [comment]
When I did not override this parameter my project simply had an error (I believe it may have been before a rules_jvm_external update). I'm checking whether I can remove this from my project.

**Comment by gergelyfabian** [comment]
It seems it's not anymore necessary. My project works without it. Thank you for the due diligence!

**Comment by shs96c** [comment]
Thank you for making the effort to put this together! I'm glad to hear that your project is working now. Happy hacking :)

**Pull request closed without merging**
