### PR TITLE
Update coursier to v2.1.0-M7

### PR DESCRIPTION
**Pull request by cheister**
Updating coursier version to address  https://github.com/bazelbuild/rules_jvm_external/issues/782

Tested by running the following
```
bazel run @unpinned_maven//:pin
bazel run @unpinned_json_artifacts_testing//:pin
bazel run @unpinned_manifest_stamp_testing//:pin
bazel run @unpinned_maven_install_in_custom_location//:pin
bazel run @unpinned_policy_pinned_testing//:pin
bazel run @unpinned_regression_testing//:pin
bazel run @unpinned_rules_jvm_external_deps//:pin
```

@jin Can you run the mirror script and then I'll update the PR to pull from `mirror.bazel.build` instead of `repo1.maven.org`

### CODE REVIEW

**Comment by srdo** [comment]
Might make sense to go to 2.1.0-RC1 instead, as it has a vulnerability fix?

https://github.com/coursier/coursier/releases/tag/v2.1.0-RC1

**Comment by jin** [comment]
So sorry to have missed this - can we bump it to 2.1.0-RC2 instead?

**Comment by jin** [comment]
I created https://github.com/bazelbuild/rules_jvm_external/pull/792 and bazel mirrored 2.1.0-RC2 there as well - PTAL.

**Comment by shs96c** [comment]
Closing this, since #792 supersedes this.

**Pull request closed without merging**
