### PR TITLE
Fix can't install maven dependencies with top-level build directory

### PR DESCRIPTION
**Pull request by cheister**
https://github.com/bazelbuild/rules_jvm_external/issues/1028

Just change the downloaded file path so it does not create a `build` directory when using http_file.

### CODE REVIEW

**Comment by shs96c** [comment]
Couldn't we just rename all our `BUILD` files to `BUILD.bazel`? That would avoid needing to do this work, and seems to be what is now common practice in the bazel OSS community (looking at the rulesets in `bazel-contrib`?

**Comment by cheister** [comment]
> Couldn't we just rename all our `BUILD` files to `BUILD.bazel`? That would avoid needing to do this work, and seems to be what is now common practice in the bazel OSS community (looking at the rulesets in `bazel-contrib`?

This isn't a problem with a BUILD file we write, it's one generated by [http_file](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl#L163)  and i[t checks if there is already a BUILD file in the path](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/http.bzl#L176), on a case-insensitive file system it compares the `build/` directory to `BUILD` and fails.  So the workaround is to not have `build/` in the downloaded_file_path passed to http_file

**Review by shs96c — APPROVED** [review]
LGTM. Thanks for the clarification. I'd missed that entirely

**Comment by cheister** [comment]
Should also address https://github.com/bazelbuild/rules_jvm_external/issues/970

**Pull request merged**
